development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pickachu
  pool: 5
  username: root
  password: 
  socket: 

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pickachu
  pool: 5
  username: root
  password: 
  socket: 
  
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: pickachu
  pool: 5
  username: root
  password: 
  socket: 